import '../models/cinematography_modals.dart';

class CinemaRepository{

  List<WorkDataModel> getFeatureWork(String filter){
    var list = {
      WorkDataModel(trailerId: "p9OUqWSqPZI",
          title: "Co-fee",
          director: "Anoop sathyan",
          category: "Commercial",
          designation1:"Director of photography",
          designation2:"",
          poster: "assets/images/cofee_app01.jpeg",
          videoPath: "",
          client: "Co-fee"),
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "PricelessSmiles",
          designation1: "Director of photography",
          designation2:"",
          director: "Nithin",
          client:"The Muthoot group",
          category: "Commercial",
          poster: "assets/images/priceless_smile07.jpg",
          videoPath: "assets/videos/priceless_smile07.mp4"),
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "PricelessSmiles",
          designation1: "Director of photography",
          designation2:"",
          director: "Nithin",
          client:"The Muthoot group",
          category: "Commercial",
          poster: "assets/images/priceless_smile06.jpg",
          videoPath: "assets/videos/priceless_smile06.mp4"),
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "PricelessSmiles",
          designation1: "Director of photography",
          designation2:"",
          director: "Nithin",
          client:"The Muthoot group",
          category: "Commercial",
          poster: "assets/images/priceless_smile01.jpg",
          videoPath: "assets/videos/priceless_smile01.mp4"),
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "PricelessSmiles",
          designation1: "Director of photography",
          designation2:"",
          director: "Nithin",
          client:"The Muthoot group",
          category: "Commercial",
          poster: "assets/images/priceless_smile02.jpg",
          videoPath: "assets/videos/priceless_smile02.mp4"),
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "PricelessSmiles",
          designation1: "Director of photography",
          designation2:"",
          director: "Nithin",
          client:"The Muthoot group",
          category: "Commercial",
          poster: "assets/images/priceless_smile03.jpg",
          videoPath: "assets/videos/priceless_smile03.mp4"),
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "PricelessSmiles",
          designation1: "Director of photography",
          designation2:"",
          director: "Nithin",
          client:"The Muthoot group",
          category: "Commercial",
          poster: "assets/images/priceless_smile04.jpg",
          videoPath: "assets/videos/priceless_smile04.mp4"),
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "PricelessSmiles",
          designation1: "Director of photography",
          designation2:"",
          director: "Nithin",
          client:"The Muthoot group",
          category: "Commercial",
          poster: "assets/images/priceless_smile05.jpg",
          videoPath: "assets/videos/priceless_smile05.mp4"),
      WorkDataModel(trailerId: "FvdGBOpMSlU",
          title: "For Alice",
          designation1: "Director of photography",
          designation2:"",
          director: "Cathy Jeethu",
          client:"Bedtime stories",
          category: "Short film",
          poster: "",
          videoPath: ""),
      WorkDataModel(trailerId: "FWg1O5byix4",
          title: "CID moosa",
          client:"Boldova Productions",
          director: "",
          designation1:"Director of photography",
          designation2:"",
          category: "Music video",
          poster: "",
          videoPath: ""),
      WorkDataModel(trailerId: "ATtlCFf82fw",
          title: "Drum devil",
          client:"",
          director: "",
          designation1:"Director of photography",
          designation2:"",
          category: "Music video",
          poster: "",
          videoPath: "assets/videos/drum_devil01.mp4"),
      WorkDataModel(trailerId: "aamCbjaaRVA",
          title: "Yoodhasinte loha",
          director: "Umesh Krishnan - Biju menon",
          client:"U - Series Imaginations & B Film Factorory",
          category: "Short film",
          designation1:"Director of photography",
          designation2:"",
          poster: "",
          videoPath: ""),
      WorkDataModel(trailerId: "Dwhp1UrXe40",
          title: "Etho varmukilin",
          director: "Jathin Sankar Raj",
          category: "Music video",
          client:"",
          poster: "",
          designation1: "Director of photography",
          designation2:"",
          videoPath: ""),
      WorkDataModel(trailerId: "yI6AhvBy2oM",
          title: "Rainbow eclipse",
          designation1: "Director of photography",
          designation2:"",
          category: "Music video",
          client:"Krishnan kurup",
          poster: "",
          director: "Audumber tapkir\nSwapnil dumbre\nSreeram nambiar",
          videoPath: ""),
      WorkDataModel(trailerId: "-5Fxe9S4NrI",
          title: "Menaka",
          designation1: "Director of photography",
          designation2:"",
          category: "Web Series",
          director: "Praveen K",
          client:"Renjith Nair",
          poster: "",
          videoPath: ""),
      WorkDataModel(trailerId: "gn0y0URMefw",
          title: "Ban plastic",
          director: "",
          client:"",
          designation1:"Director of photography",
          designation2:"",
          category: "Commercial",
          poster: "",
          videoPath: ""),
      // WorkDataModel(trailerId: "LLjLGWoKJ34",
      //     title: "Ashiyan",
      //     director: "Nithin",
      //     client:"The Muthoot group",
      //     category: "Commercial",
      //     poster: "",
      //     videoPath: "",
      //     designation: "Director of photography"),
    }.toList();

    return list.where((i) => i.category == filter).toList();
  }

  List<WorkDataModel> getHomeData(){
    return [
      WorkDataModel(trailerId: "8KHm0PcVN2I",
          title: "Priceless smile",
          director: "",
          client:"",
          designation1:"Director of photography",
          designation2:"",
          category: "Commercial",
          poster: "https://img.youtube.com/vi/8KHm0PcVN2I/0.jpg",
          videoPath: "assets/videos/priceless_smile01.mp4"),
      WorkDataModel(trailerId: "FvdGBOpMSlU",
          title: "For Alice",
          director: "Cathy Jeethu",
          client:"Bedtime stories",
          designation1:"Director of photography",
          designation2:"",
          category: "Short film",
          poster: "https://img.youtube.com/vi/FvdGBOpMSlU/0.jpg",
          videoPath: ""),
      WorkDataModel(trailerId: "FWg1O5byix4",
          title: "CID moosa",
          director: "",
          client:"Boldova Productions",
          designation1:"Director of photography",
          designation2:"",
          category: "Music video",
          poster: "https://img.youtube.com/vi/FWg1O5byix4/0.jpg",
          videoPath: ""),
      WorkDataModel(trailerId: "GkAUsuGMqm8",
          title: "Hrudayapoorvam",
          director: "",
          client: "Aashirvad",
          designation1:"Associate cameraman",
          designation2:"",
          category: "Associated film",
          poster: "https://img.youtube.com/vi/GkAUsuGMqm8/0.jpg",
          videoPath: ""),
      WorkDataModel(trailerId: "Ilrs-OWSpuY",
          title: "Seematti",
          director: "",
          client: "Seematti",
          designation1:"Associate cameraman",
          designation2:"",
          category: "Associated commercial",
          poster: "https://img.youtube.com/vi/Ilrs-OWSpuY/0.jpg",
          videoPath: ""),
    ];
  }

  List<WorkDataModel> getFilms(){
    return {
      WorkDataModel(
        category: "Associated film",
        trailerId: "GkAUsuGMqm8",
          title: "Hrudayapoorvam (2025)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
          ),
      WorkDataModel(
        category: "Associated film",
          trailerId: "ubVjt3eIDqA",
          title: "Padakkalam (2025)",
          designation1: "Second Unit Cinematographer",
          designation2:"Chief Associate Cinematographer",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "PGqltBCo6cU",
          title: "L2:Empuran (2025)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
        category: "Web series",
        trailerId: "QPuOLNzPR7k",
        title: "Perilloor Premier League (2024)",
          designation1: "Second Unit Cinematographer",
          designation2:"Associate Cinematographer",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
        category: "Associated film",
        trailerId: "dljEVygvwG8",
        title: "King of Kotha (2023)",
        designation1: "Additional Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "OCGGoT23kh4",
          title: "Kooman (2022)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "uUJtUYkBu-g",
          title: "Dhrishyam 2 (2021)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "L13AUL0HkDk",
          title: "Kurup (2021)",
          designation1: "Second Unit Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "4DTsMtDcbNo",
          title: "Athiran (2019)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "v0-J9V6bZS8",
          title: "Padayottam (2018)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "8-vWm6cDnak",
          title: "Aadhi (2018)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "f9ym_s-CEmI",
          title: "Tiyaan (2017)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      ),
      WorkDataModel(
          category: "Associated film",
          trailerId: "cunn6W_9MM0",
          title: "Ore Mukham (2016)",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "",
          videoPath: ''
      )
    }.toList();
  }

  List<WorkDataModel> getCommercials(){
    return {
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "l4KadPBOa98",
          title: "Goldmedal",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "Goldmedal",
          videoPath: ""
      ),
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "90RcJ0udpKc",
          title: "Goldmedal",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "Goldmedal",
          videoPath: ""
      ),
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "HaXVOBi2Y30",
          title: "PhonePe",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "PhonePe",
          videoPath: ""
      ),
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "fFwOgt3YO1U",
          title: "PhonePe",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "PhonePe",
          videoPath: ""
      ),
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "DIALEvmlhDQ",
          title: "Colgate",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "Colgate",
          videoPath: ""),
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "2A5Krtb310o",
          title: "Colgate",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "Colgate",
          videoPath: ""),
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "pViKP5JnM2w",
          title: "Colgate",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "Colgate",
          videoPath: ""),
      WorkDataModel(
          category: "Associated commercial",
          trailerId: "Ilrs-OWSpuY",
          title: "Seematti",
          designation1: "Associate Cinematographer",
          designation2:"",
          poster: "",
          director: "",
          client: "Seematti",
          videoPath: "")
    }.toList();
  }
}