import '../models/cinematograpghy_modals.dart';

class CinemaRepository{

  List<Trailer> getFeaturefilms(){
    return {
      Trailer(trailerId: "FvdGBOpMSlU",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
    }.toList();
  }

  List<Trailer> getFilms(){
    return {
      Trailer(trailerId: "GkAUsuGMqm8",
          filmName: "Hrudayapoorvam",
          yearOfRelease: "2025",
          directorName: "Sathyan Andikad",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "Aashirvad cinemas",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "ubVjt3eIDqA",
          filmName: "Padakkalam",
          yearOfRelease: "2025",
          directorName: "Manu swaraj",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "Friday film house",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "PGqltBCo6cU",
          filmName: "L2:Empuram",
          yearOfRelease: "2025",
          directorName: "Prithviraj sukumaran",
          dopName: "Sujith Vasudev",
          myDesignation: "Associate DOP",
          productionHouse: "Aashirvad Cinemas, Lyca productions",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "OCGGoT23kh4",
          filmName: "Kooman",
          yearOfRelease: "2022",
          directorName: "Jeethu joseph",
          dopName: "Satheesh kurup",
          myDesignation: "Associate DOP",
          productionHouse: "Magic Frames, Ananya Films",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "uUJtUYkBu-g",
          filmName: "Dhrishyam 2",
          yearOfRelease: "2021",
          directorName: "Jeethu joseph",
          dopName: "Satheesh kurup",
          myDesignation: "Associate DOP",
          productionHouse: "Suresh Productions, RajKumar Theatres, Aashirvad Cinemas",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg",
          }.toList()),
      Trailer(trailerId: "L13AUL0HkDk",
          filmName: "Kurup",
          yearOfRelease: "2021",
          directorName: "Srinath Rajendran",
          dopName: "Nimish Ravi",
          myDesignation: "Associate DOP",
          productionHouse: "Wayfarer Films,M Star Entertainments",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "4DTsMtDcbNo",
          filmName: "Padayottam",
          yearOfRelease: "2019",
          directorName: "	Rafeek Ibrahim",
          dopName: "Satheesh Kurup",
          myDesignation: "Associate DOP",
          productionHouse: "Weekend Blockbusters",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "8-vWm6cDnak",
          filmName: "Aadhi",
          yearOfRelease: "2018",
          directorName: "Jeethu joseph",
          dopName: "Satheesh kurup",
          myDesignation: "Associate DOP",
          productionHouse: "Aashirvad Cinemas",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "f9ym_s-CEmI",
          filmName: "Tiyaan",
          yearOfRelease: "2017",
          directorName: "Jiyen Krishnakumar",
          dopName: "Satheesh kurup",
          myDesignation: "Associate DOP",
          productionHouse: "Red Rose Creations",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "cunn6W_9MM0",
          filmName: "Ore Mukham",
          yearOfRelease: "2016",
          directorName: "Sajith Jagadnandan",
          dopName: "Satheesh kurup",
          myDesignation: "Assistant DOP",
          productionHouse: "Backwater Studios",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg",
          }.toList())
    }.toList();
  }

  List<Trailer> getShortFilms(){
    return {Trailer(trailerId: "FvdGBOpMSlU",
        filmName: "Athiran",
        yearOfRelease: "2021",
        directorName: "Director",
        dopName: "Anu moothedath",
        myDesignation: "Associate DOP",
        productionHouse: "House",
        photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
    }.toList();
  }

  List<Trailer> getMusicals(){
    return {Trailer(trailerId: "yI6AhvBy2oM",
        filmName: "Athiran",
        yearOfRelease: "2021",
        directorName: "Director",
        dopName: "Anu moothedath",
        myDesignation: "Associate DOP",
        productionHouse: "House",
        photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "FWg1O5byix4",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "Dwhp1UrXe40",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
    }.toList();
  }

  List<Trailer> getWebSeries(){
    return {Trailer(trailerId: "QPuOLNzPR7k",
        filmName: "Perilloor Premier League",
        yearOfRelease: "2021",
        directorName: "Praveen Chandran",
        dopName: "Anoop V. Shylaja",
        myDesignation: "Associate DOP",
        productionHouse: "House",
        photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
    }.toList();
  }

  List<Trailer> getNarratives(){
    return {Trailer(trailerId: "0H2QxxK2E3E",
        filmName: "Athiran",
        yearOfRelease: "2021",
        directorName: "Director",
        dopName: "Anu moothedath",
        myDesignation: "Associate DOP",
        productionHouse: "House",
        photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "l_gAGqwNSEA",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "fHZnIoSdUpI",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "OzxKTeW1ChE",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
    }.toList();
  }
  List<Trailer> getCommercials(){
    return {Trailer(trailerId: "8KHm0PcVN2I",
        filmName: "Athiran",
        yearOfRelease: "2021",
        directorName: "Director",
        dopName: "Anu moothedath",
        myDesignation: "Associate DOP",
        productionHouse: "House",
        photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "uR6xRGn3oWJgUcNz",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "Ilrs-OWSpuY",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "zx84CMN1qPA",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList())
    }.toList();
  }
  List<Trailer> getIndeCommercials(){
    return {Trailer(trailerId: "p9OUqWSqPZI",
        filmName: "Athiran",
        yearOfRelease: "2021",
        directorName: "Director",
        dopName: "Anu moothedath",
        myDesignation: "Associate DOP",
        productionHouse: "House",
        photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "8KHm0PcVN2I&t=176s",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "gn0y0URMefw",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
      Trailer(trailerId: "LLjLGWoKJ34",
          filmName: "Athiran",
          yearOfRelease: "2021",
          directorName: "Director",
          dopName: "Anu moothedath",
          myDesignation: "Associate DOP",
          productionHouse: "House",
          photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList()),
    Trailer(trailerId: "LLjLGWoKJ34",
        filmName: "Athiran",
        yearOfRelease: "2021",
        directorName: "Director",
        dopName: "Anu moothedath",
        myDesignation: "Associate DOP",
        productionHouse: "House",
        photoPaths: {"assets/images/image4.jpeg","assets/images/image3.jpeg","assets/images/image2.jpeg"}.toList())
  }.toList();
  }
}